language: node_js
dist: trusty
addons:
  chrome:
     stable

node_js:
  - "node"

before_install:
  - npm start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - npm -v
  - node -v
